name: passportapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dotted_border: ^2.0.0+2
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  firebase_auth: ^3.4.2
  google_sign_in: ^5.4.0
  location: ^4.4.0
  geocoding: ^2.0.4
  shared_preferences: ^2.0.15
  http: ^0.13.4
  share_plus: ^4.0.10
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/appleIcon.png
    - assets/images/googleIcon.png
    - assets/images/heartIcon.png
    - assets/images/heartIcon_grey.png
    - assets/images/searchIcon.png
    - assets/images/notificationIcon.png
    - assets/images/backButton.png
    - assets/images/locationOnBoard.png
    - assets/images/redeemIcon.png
    - assets/images/saveIcon.png
    - assets/images/unsaveIcon.png
    - assets/images/shareIcon.png
    - assets/images/deal_info.png
    - assets/images/deal_info_bg.png
    - assets/images/weather_sunny.png
    - assets/images/idea.png
    - assets/images/goldPot.png
    - assets/images/profilePic.png
    - assets/images/pinLocation.png
    - assets/images/pinLocation_outlined.png
    - assets/images/account_info.png
    - assets/images/account_deals.png
    - assets/images/account_chat.png
    - assets/images/account_preferences.png
    - assets/images/account_notifications.png
    - assets/images/filled_home.png
    - assets/images/filled_search.png
    - assets/images/filled_redeem.png
    - assets/images/filled_profile.png
    - assets/images/outlined_home.png
    - assets/images/outlined_search.png
    - assets/images/outlined_redeem.png
    - assets/images/outlined_profile.png
    - assets/images/categories/attractions.png
    - assets/images/categories/beach.png
    - assets/images/categories/transportation.png
    - assets/images/categories/events.png
    - assets/images/categories/familyfun.png
    - assets/images/categories/fishing.png
    - assets/images/categories/golf.png
    - assets/images/categories/lodging.png
    - assets/images/categories/shopping.png
    - assets/images/categories/shows.png
    - assets/images/categories/watersport.png
    - assets/images/categories/wellness.png
    - assets/images/categories/breakfast.png
    - assets/images/categories/brewpub.png
    - assets/images/categories/buffet.png
    - assets/images/categories/burgers&wings.png
    - assets/images/categories/delivery.png
    - assets/images/categories/familydining.png
    - assets/images/categories/finedining.png
    - assets/images/categories/oceanfront.png
    - assets/images/categories/pizza.png
    - assets/images/categories/seafood.png
    - assets/images/categories/sportsbar.png
    - assets/images/categories/steakhouse.png

  fonts:
    - family: Actor
      fonts:
        - asset: assets/fonts/Actor-Regular.ttf

